public class basic {
    public static void main(String [] args)
    {
        int a,b,d,c=0,e=0,f=0,p,q,r,ar,l,br,para,sq,are,par;
        float add,sub,pro,div,si=0,prin,rate,t,arr,hi,ba,rd,acir,cir;
    a=Integer.parseInt(args[0]);
    b=Integer.parseInt(args[1]);
    d=Integer.parseInt(args[2]);
    prin=Float.parseFloat(args[0]);
    rate=Float.parseFloat(args[1]);
    t=Float.parseFloat(args[2]);
    hi=Float.parseFloat(args[5]);
    ba=Float.parseFloat(args[6]);
    rd=Float.parseFloat(args[7]);
    System.out.println("integer value="+a);
    System.out.println("integer value="+b);
    System.out.println("integer value="+d);
    System.out.println("principal amount="+prin);
    System.out.println("rate of interest="+rate);
    System.out.println("time="+t);
    System.out.println("height of triangle="+hi);
    System.out.println("base of triangle="+ba);
    System.out.println("radius of circle="+rd);

    System.out.println("hello world");
    System.out.println("abcdefxyz");
    System.out.println("hello world");
    int i =10;
    System.out.println("integer="+i);
    System.out.println("hello world");
    c=a+b;
    System.out.println("sum of two integer value="+c);
    e=a+b+d;
    System.out.println("sum of three integer value="+e);
    f=a-b;
    System.out.println("subtraction of two integer value="+f);
    p=a*b;
    System.out.println("multiplication of two integer value="+p);
    q=d/b;
    System.out.println("division of two integer value="+q);
    r=d%b;
    System.out.println("modulus of two integer value="+r);
    char ch='A';
    System.out.println("character="+ch);
    float g=10.5f;
    System.out.println("float value="+g);
    float h=20.99f;
    System.out.println("double value="+h);
    add=g+h;
    System.out.println("sum of float and double value="+add);
    sub=h-g;
    System.out.println("subtraction of double and float value="+sub);
    pro=g*h;
    System.out.println("multiplication of float and double value="+pro);
    div=h/g;
    System.out.println("division of double and float value="+div);
    si=(prin*rate*t)/100;
    System.out.println("simple interest="+si);
    l=Integer.parseInt(args[3]);
    br=Integer.parseInt(args[4]);
    System.out.println("length of rectangle="+l);
    System.out.println("breadth of rectangle="+br);
    ar=l*br;
    System.out.println("area of rectangle="+ar);
    para=2*(l+br);
    System.out.println("perimeter of rectangle="+para);
    sq=Integer.parseInt(args[3]);
    System.out.println("side of square="+l);
    are=sq*sq;
    System.out.println("area of square="+are);
    par=4*sq;
    System.out.println("perimeter of square="+par);
    arr=0.5f*hi*ba;
    System.out.println("area of triangle="+arr);
    acir=3.14f*rd*rd;
    System.out.println("area of circle="+acir);
    cir=2*3.14f*rd;
    System.out.println("circumference of circle="+cir);
    int cha =i=i-1;
    int cha1=i--;
    System.out.println("value of cha="+cha);
    System.out.println("value of cha1="+cha1);
    System.out.println("cha1 is same as cha because in cha i is decremented first and then assigned to cha but in cha1 the value of i is assigned to cha1 first and then i is decremented");
    a+=2;
    System.out.println("a+=2 is="+a);
    a=a+2;
    System.out.println("a=a+2 is="+a);
    System.out.println("a+=2 is same as a=a+2");
    a-=2;
    System.out.println("a-=2 is="+a);
    a=a-2;
    System.out.println("a=a-2 is="+a);
    System.out.println("a-=2 is same as a=a-2");
    a*=2;
    System.out.println("a*=2 is="+a);
    a=a*2;
    System.out.println("a=a*2 is="+a);
    System.out.println("a*=2 is same as a=a*2");
    a/=2;   
    System.out.println("a/=2 is="+a);
    a=a/2;
    System.out.println("a=a/2 is="+a);
    System.out.println("a/=2 is same as a=a/2");
}
}